"use client";

import { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Loader2, RefreshCw, ChevronDown, ChevronUp, Clock } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { summariesApi } from "@/lib/api";
import { formatTimestamp } from "@/lib/utils";
import type { SummaryDetail } from "@/lib/types";

interface SummaryPanelProps {
  meetingId: string;
  summary: SummaryDetail | null;
  status: string;
  onChapterSeek: (seconds: number) => void;
}

export function SummaryPanel({ meetingId, summary, status, onChapterSeek }: SummaryPanelProps) {
  const qc = useQueryClient();
  const [chaptersOpen, setChaptersOpen] = useState(true);

  const regen = useMutation({
    mutationFn: () => summariesApi.regenerate(meetingId),
    onSuccess: () => {
      toast.info("Generating summary with AI...", { duration: 4000 });
      // Poll until ready
      const interval = setInterval(async () => {
        qc.invalidateQueries({ queryKey: ["meeting", meetingId] });
        const d = qc.getQueryData<{ summary?: SummaryDetail; status?: string }>(["meeting", meetingId]);
        if (d?.status === "ready") clearInterval(interval);
      }, 2000);
      setTimeout(() => clearInterval(interval), 60000);
    },
    onError: () => toast.error("Failed to start summary generation"),
  });

  if (status === "processing") {
    return (
      <div className="space-y-3 p-4">
        <Skeleton className="h-4 w-32" />
        <Skeleton className="h-4 w-full" />
        <Skeleton className="h-4 w-5/6" />
        <Skeleton className="h-4 w-4/6" />
        <div className="flex items-center gap-2 pt-2 text-sm text-muted-foreground">
          <Loader2 className="h-4 w-4 animate-spin text-brand-500" />
          Generating AI summary…
        </div>
      </div>
    );
  }

  if (!summary) {
    return (
      <div className="flex flex-col items-center justify-center gap-4 py-12 text-center px-4">
        <p className="text-sm text-muted-foreground">
          AI summary has not been generated yet.
        </p>
        <Button
          onClick={() => regen.mutate()}
          disabled={regen.isPending}
          className="bg-brand-500 text-white hover:bg-brand-600"
          size="sm"
        >
          {regen.isPending ? (
            <><Loader2 className="mr-2 h-4 w-4 animate-spin" />Generating…</>
          ) : (
            "Generate Summary"
          )}
        </Button>
      </div>
    );
  }

  return (
    <div className="space-y-5 p-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <p className="text-xs text-muted-foreground">
            Generated by{" "}
            <span className="font-medium text-brand-500">{summary.generated_by.replace(" (seeded)", "")}</span>
          </p>
        </div>
        <Button
          variant="ghost"
          size="sm"
          onClick={() => regen.mutate()}
          disabled={regen.isPending}
          aria-label="Regenerate summary"
        >
          <RefreshCw className={`h-3.5 w-3.5 ${regen.isPending ? "animate-spin" : ""}`} />
        </Button>
      </div>

      {/* Overview */}
      <div className="space-y-2">
        {summary.overview.split("\n\n").map((para, i) => (
          <p key={i} className="text-sm leading-relaxed text-gray-700 dark:text-gray-300">
            {para}
          </p>
        ))}
      </div>

      {/* Chapters */}
      {summary.chapters.length > 0 && (
        <div className="border-t border-surface-border pt-4 dark:border-sidebar-hover">
          <button
            className="flex w-full items-center justify-between text-sm font-semibold text-gray-900 dark:text-white"
            onClick={() => setChaptersOpen((o) => !o)}
            aria-expanded={chaptersOpen}
          >
            Chapters
            {chaptersOpen ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
          </button>
          {chaptersOpen && (
            <div className="mt-3 space-y-3">
              {summary.chapters.map((ch, i) => (
                <div key={i} className="flex gap-3">
                  <div className="mt-1 flex flex-col items-center">
                    <div className="h-2.5 w-2.5 rounded-full bg-brand-500" />
                    {i < summary.chapters.length - 1 && (
                      <div className="mt-1 w-px flex-1 bg-brand-200 dark:bg-brand-500/20" />
                    )}
                  </div>
                  <div className="pb-3">
                    <div className="flex items-center gap-2 flex-wrap">
                      <p className="text-sm font-medium text-gray-900 dark:text-white">{ch.title}</p>
                      <button
                        onClick={() => onChapterSeek(ch.start_seconds)}
                        className="inline-flex items-center gap-1 text-[11px] text-brand-500 hover:text-brand-600 font-mono"
                        aria-label={`Jump to chapter at ${formatTimestamp(ch.start_seconds)}`}
                      >
                        <Clock className="h-3 w-3" />
                        {formatTimestamp(ch.start_seconds)}
                      </button>
                    </div>
                    <p className="mt-0.5 text-xs text-muted-foreground">{ch.summary}</p>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
